# Generated by Django 5.2.17 on 2026-08-04 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_lesson_lessontask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название класса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_class_groups', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Учитель')),
                ('lesson', models.ForeignKey(blank=True, help_text='Если урок указан, его задачи добавляются в задание', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tasks.lesson', verbose_name='Урок')),
                ('students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='direct_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ученики')),
                ('tasks', models.ManyToManyField(blank=True, related_name='assignments', to='tasks.task', verbose_name='Задачи')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.classgroup', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, max_length=500, verbose_name='Краткий ответ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='submissions/', verbose_name='Изображение')),
                ('code', models.TextField(blank=True, verbose_name='Код решения')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('status', models.CharField(choices=[('correct', 'Верно'), ('incorrect', 'Неверно'), ('ok', 'OK'), ('wa', 'Неправильный ответ'), ('tle', 'Превышено время'), ('re', 'Ошибка выполнения'), ('ce', 'Ошибка компиляции'), ('pending', 'На проверке'), ('accepted', 'Зачтено'), ('rejected', 'Не зачтено')], default='pending', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='tasks.answeroption', verbose_name='Выбранный вариант')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment', verbose_name='Задание')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ('-created_at',),
            },
        ),
    ]
