# Generated by Django 5.2.17 on 2026-08-31 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Токен приглашения'),
        ),
    ]
