# Generated by Django 5.2.17 on 2026-08-04 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текстовая'), ('image', 'С картинкой'), ('programming', 'Программирование')], default='text', max_length=16, verbose_name='Тип задачи')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], default='medium', max_length=8, verbose_name='Сложность')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('body', models.TextField(blank=True, verbose_name='Условие')),
                ('image', models.ImageField(blank=True, help_text='Для задач с картинкой или иллюстрация к условию', null=True, upload_to='tasks/', verbose_name='Изображение')),
                ('answer_mode', models.CharField(choices=[('choice', 'Выбор ответа'), ('short', 'Краткий ответ')], default='choice', help_text='Только для текстовых задач', max_length=8, verbose_name='Тип ответа')),
                ('correct_answer', models.CharField(blank=True, help_text='Для краткого ответа (сравнение строгое, без учёта регистра)', max_length=500, verbose_name='Правильный ответ')),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=16, verbose_name='Язык программирования')),
                ('time_limit_ms', models.PositiveIntegerField(default=1000, verbose_name='Лимит времени, мс')),
                ('memory_limit_mb', models.PositiveIntegerField(default=128, verbose_name='Лимит памяти, МБ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='', verbose_name='Входные данные')),
                ('expected_output', models.TextField(blank=True, default='', verbose_name='Ожидаемый вывод')),
                ('is_public', models.BooleanField(default=True, help_text='Открытые тесты видны ученику, закрытые — только для проверки', verbose_name='Открытый тест')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ('order', 'id'),
            },
        ),
    ]
