# Generated by Django 5.2.17 on 2026-08-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_topic_task_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.CharField(choices=[('author', 'Авторская'), ('kompege', 'Kompege'), ('yandex', 'Yandex'), ('kpolyakov', 'Kpolyakov'), ('other', 'Другое')], default='author', max_length=16, verbose_name='Источник задачи'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, help_text='Генерируется автоматически: номер_темы_порядковый_номер', max_length=32, verbose_name='Номер задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='answer_mode',
            field=models.CharField(choices=[('choice', 'Выбор ответа'), ('short', 'Краткий ответ')], default='short', help_text='Только для текстовых задач', max_length=8, verbose_name='Тип ответа'),
        ),
    ]
